### ISSUE TITLE
Please FIX for beatmania IIDX

### ISSUE THREAD

**Issue by JerryDaga** [asphyxia-core/plugins#24]
Please FIX for Beatmania IIDX
like creating an account and save scores and many more.
Cannon Baller, Rootage, and Herotic Verse also the new release Bistrovers

**Comment by TsFreddie** [comment]
We don't have community plugins (meaning in this repo) for IIDX. There are third party ones in our discords. Also, n-0 release won't get plugin releases from this repo.
