### ISSUE TITLE
(New suggestion)

### ISSUE THREAD

**Issue by JerryDaga** [asphyxia-core/plugins#33]
Please, Make a Plugins supports Codes for Beatmania IIDX Sinobuz to the Latest version and Dance Evolution too.
Please.

**Comment by TsFreddie** [comment]
Again. We don't have IIDX plugins yet. no one is contributing.

**Comment by JerryDaga** [comment]
but i have a plugins file i don't know how to operate it i don't know if
the game have a service lock or did not support the asphyxia

**Comment by TsFreddie** [comment]
then ask the plugin author. we have no idea where you got your iidx plugin or who made it.

**Comment by JerryDaga** [comment]
Ok, I'll check it out.

**Comment by JerryDaga** [comment]
Here the Beatmania IIDX plugins files. Supported on IIDX 27 Heroic Verse.
And I hope you can do that to manage it..
I want to play with save service or data

**Comment by TsFreddie** [comment]
Email attachments won't be uploaded to GitHub automatically. But you shouldn't share unlisenced code publicly without author's consent. 

Again, you should contact the plugin's author instead of here.

Closing the issues because you shouldn't be sending codes that is not yours.
