### ISSUE TITLE
[GITADORA] Capitalization in Gitadora plugin making it incompatible with Linux

### ISSUE THREAD

**Issue by F0cket** [asphyxia-core/plugins#51]
Line 11 of handlers/profiles.ts has "Utils" instead of "utils" causing the plugin to fail to load in Linux environments where directories are case sensitive.

**Comment by dannylin0711** [comment]
https://github.com/asphyxia-core/plugins/blob/5ad309c1af3642db0ff7c511970ca3b5e48a252a/gitadora%40asphyxia/handlers/profiles.ts#L11

This line?

**Comment by F0cket** [comment]
> https://github.com/asphyxia-core/plugins/blob/5ad309c1af3642db0ff7c511970ca3b5e48a252a/gitadora%40asphyxia/handlers/profiles.ts#L11
> 
> This line?

That's the one.
