### ISSUE TITLE
SDVX Crash with Multiple Profiles

### ISSUE THREAD

**Issue by MusicalPulse** [asphyxia-core/plugins#59]
SDVX will crash if Asphyxia has multiple profiles. Another discord user I was talking to also solved the issue by deleting all but 1 profile. They were using the same card for both profiles, but I was using a virtual card for one and a real card for another. 

The error https://cdn.discordapp.com/attachments/1107580183923392603/1117644474756112454/20230611_141711.jpg

We were both using the plugin fork from https://github.com/22vv0/asphyxia_plugins , so I don't know if that or the program itself is causing the issue.

**Comment by anjing-puteh** [comment]
try using pr2 for 22vv0 fork instead.

**Comment by dannylin0711** [comment]
This is an n-0 problem, will not be resolve in this repo until the game is out n-0 state.

**Comment by dannylin0711** [comment]
> try using pr2 for 22vv0 fork instead.

This person is already using that fork.

**Comment by dannylin0711** [comment]
If you're sure about the version you use is not n-0, upload your log.txt.

**Comment by MusicalPulse** [comment]
I was using the stable version of the fork, not the PR2 branch. I haven't actually tested another profile yet, but I see that it was fixed in a merge, so it should work.
