### ISSUE TITLE
[SDVX] How to save progress? Got card but always "GUEST"

### ISSUE THREAD

**Issue by RetroGameTalk** [asphyxia-core/plugins#68]
I can't get SDVX to save my progress, the ping is recognized but each time I'm asked to enter a nickname and after playing 3 songs and saving the progress is lost and the I have to redo everything as if it's the first time I play.

**Comment by dannylin0711** [comment]
Need more information to identify what the problem is, you may join asphyxia for support, as this require some of the debug files and need some tinkering to the launcher settings. Sorry for the inconvenience.

First of all, which version of the plugin are you using?

**Comment by RetroGameTalk** [comment]
Sorry to bother I decided to play in konaste it solved all my issues.
